name: Automated-Deploy-Lambda-Function

on:
  push:
    branches:
      - 'hotfix'
jobs:
  hotfix:
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, 'hotfix') }}
    defaults:
      run:
        working-directory: ./hotfix

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lambda function zip
        run: zip -r hotfix-resized.zip ./index.js ./package.json ./package-lock.json ./node_modules

      - name: Deploy lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: default-deploy
          zip_file: ./hotfix/hotfix-resized.zip
          dry_run: true
          debug: true
          memory_size: 512
          timeout: 30
          handler: index.handler
          role: ${{ secrets.LAMBDA_FUNCTION_ROLE }}
          runtime: nodejs16.x

  comment:
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, 'comment') }}
    defaults:
      run:
        working-directory: ./comment-resizing

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lambda function zip
        run: zip -r comment-resized.zip ./index.js ./package.json ./package-lock.json ./node_modules

      - name: Deploy lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: default-deploy-2
          zip_file: ./comment-resizing/comment-resized.zip
          dry_run: true
          debug: true
          memory_size: 512
          timeout: 30
          handler: index.handler
          role: ${{ secrets.LAMBDA_FUNCTION_ROLE }}
          runtime: nodejs16.x
