name: Lambda CI

on:
  push:
    branches: ['main']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: aws-lambda zip
        run: zip -r aws-lambda.zip ./index.js ./package.json ./package-lock.json

      - name: unzip
        run: unzip aws-lambda.zip

      - name: npm i
        run: npm i

      - name: zip
        run: ./node_modules ./index.js ./package.json ./package-lock.json