name: Lambda CI

on:
  push:
    branches: ['test']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: zip
        run: zip -r aws-lambda.zip ./comment-resizing ./package.json ./package-lock.json

      - name: remove folder
        run: rm -rf comment-resizing

      - name: unzip 
        run: unzip aws-lambda.zip

      - name: cd
        run: cd comment-resizing

      - name: npm i
        run: npm i

      - name: aws upload zip
        run: zip -r aws-lambda.zip ./*

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: aws upload
        run: aws s3 cp "aws-lambda.zip" s3://${{ secrets.AWS_BUCKET }}