name: Automated-Deploy-Lambda-Function

on:
  push:
    branches:
      - 'test'
jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, 'comment') }}
    defaults:
      run:
        working-directory: ./comment-resizing

    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: zip
        run: zip -r comment.zip ./index.js
    
      - name: ls
        run: ls
