name: Lambda CI

on:
  push:
    branches: 'test'

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, 'profile') }}
    defaults:
      run:
        working-directory: ./profile-resizing

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Set up aws-sdk
        run: npm ci aws-sdk
    
      - name: Set up sharp
        run: npm ci sharp

      - name: Lambda function zip
        run: zip -r profile-resized-${{github.event.pull_request.timestamp}}.zip 

      - name: Deploy lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: default-deploy
          zip_file: ./profile-resized-${{github.event.pull_request.timestamp}}.zip
          dry_run: true
          debug: true
          memory_size: 512
          timeout: 30
          handler: index.handler
          role: ${{ secrets.LAMBDA_FUNCTION_ROLE }}
          runtime: nodejs16.x
