name: Lambda CI

on:
  push:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, 'profile') }}
    defaults:
      run:
        working-directory: ./profile-resizing

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lambda function zip
        run: zip -r profile-resized.zip ./index.js ./package.json ./package-lock.json ./node_modules

      - name: ls
        run: ls

      - name: Deploy lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: default-deploy
          zip_file: ./profile-resizing/profile-resized.zip
          dry_run: true
          debug: true
          memory_size: 512
          timeout: 30
          handler: index.handler
          role: ${{ secrets.LAMBDA_FUNCTION_ROLE }}
          runtime: nodejs16.x