name: Automated-Deploy-Lambda-Function

on:
  push:
    branches:
      - 'main'
jobs:
  job:
    build:
      runs-on: ubuntu-20.04
      if: ${{ contains(github.event.head_commit.message, 'profile') }}
      defaults:
        run:
          working-directory: ./profile-resizing

      steps:
        - name: zip
          run: zip -r profile.zip ./index.js
      
        - name: ls
          run: ls
