name: Lambda CI

on:
  pull_request:
    branches: 'feature/profile-resizing'

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.ref_name == 'feature/profile-resizing'
    defaults:
      run:
        working-directory: ./profile-resizing

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: npm
        uses: npm i
      
      - name: zip
        uses: zip -r test.zip ./node_modules

      - name: check
        uses: ls