name: Lambda CI

on:
  push:
    branches: ['main']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: zip
        run: zip -r aws-lambda.zip ./comment-resizing

      - name: upload s3
        run: aws s3 cp ./aws-lambda.zip s3://cupick-images