name: Lambda CI

on:
  push:
    branches: ['main']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: zip
        run: zip -r aws-lambda.zip ./comment-resizing

      - name: awscli
        run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

      - name: unzip
        run: unzip awscliv2.zip

      - name: aws configure
        run: aws configure
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          default-region-name: ${{ secrets.AWS_REGION }}
          default-output-format: ${{ secrets.AWS_FORMAT }}

      - name: uploa
        run: aws s3 cp "aws-lambda.zip" s3://cupick-images
