name: Lambda CI

on:
  push:
    branches: ['test']

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: remove exist node_modules
        run: rm -rf node_modules
        working-directory: profile-resizing

      - name: set up
        run: npm i
        working-directory: profile-resizing

      - name: profile-lambda zip
        run: zip -r profile-lambda.zip ./*
        working-directory: profile-resizing
      
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: aws-upload
        run: aws s3 cp "profile-lambda.zip" s3://${{ secrets.AWS_BUCKET }}